# Generated by Django 3.2.7 on 2021-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_examination_plan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='plan_file',
            field=models.FilePathField(path='D:\\Projects\\Python\\NewTest\\testing\\source/plans'),
        ),
    ]
