# Generated by Django 3.2.7 on 2021-10-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_examination_plan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='plan_file',
            field=models.FileField(upload_to='plans'),
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(upload_to='files'),
        ),
    ]
