# Generated by Django 3.2.7 on 2021-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20211017_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='plan_file',
            field=models.FileField(upload_to='plans<function Examination.upload_path at 0x0000015ADF57B310>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(upload_to='files<function File.upload_path at 0x0000015ADF57B670>'),
        ),
    ]
