# Generated by Django 3.2.7 on 2021-10-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20211017_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='plan_file',
            field=models.FileField(upload_to='plans'),
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(upload_to='files'),
        ),
    ]
